cookie:
  expiry_days: 30
  key: "some_secret_key_that_is_very_long" # Mude esta chave!
  name: "your_app_cookie"

credentials:
  usernames:
    gabriel: # Seu nome de usuário
      email: "gabriel@assesi.com"
      name: "Gabriel"
      password: "admin"
      
      wendel: # Seu nome de usuário
      email: "wendel@assesi.com"
      name: "Wendel"
      password: "andrade1994"

      neto: # Seu nome de usuário
      email: "raimundo.neto@assesi.com"
      name: "Neto"
      password: "neto123"

      kauan: # Seu nome de usuário
      email: "kauan@assesi.com"
      name: "Kauan"
      password: "kauan123"      
    
      thomas: # Seu nome de usuário
      email: "thomas@assesi.com"
      name: "Thomas"
      password: "thomas"

      thilia: # Seu nome de usuário
      email: "thilia@assesi.com"
      name: "Thilia"
      password: "thilia123"
      
      
      # Cuidado: a senha aqui deve ser um hash, não texto puro!
    # adicione outros usuários aqui
    # outro_usuario:
    #   email: "outro@example.com"
    #   name: "Outro Nome"

    #   password: "def"
