# Arquivo: .streamlit/secrets.toml

# 1. Configuração do Banco de Dados Local (SQLite)
[database_local]
type = "sqlite"
path = "data/database.db"

# 2. Credenciais de Login dos Usuários (use as senhas criptografadas)
[credentials.usernames.assesi]
email = "atendimento@assesi.com"
name = "Assesi Brasil"
password = "$2b$12$4W7vCIr9jROoMfRVwSdacuzYj39Qdx//WfNEbko4EGbgVzW9nEBBq"

[credentials.usernames.rbriggs]
email = "gabriel@assesi.com"
name = "Gabriel"
password = "$2b$12$tUPq6qP15ypp4x/mYLE6xedO1L7UriJIm98vGZCFbaLz7fKHnokbq"

# 3. Configuração do Cookie de Autenticação
[cookie]
name = "avaliapntp_cookie_local"
key = "uma_chave_secreta_para_teste_local_123"
expiry_days = 30
